Endothelial:
- endothelial cell
- tip cell
Epithelial:
- epithelial cell
- gut absorptive cell
- keratin accumulating cell
Germ line:
- germ line cell
Glial:
- glial cell
Hematopoietic:
- follicular dendritic cell
- hematopoietic cell
Mesenchymal/stromal:
- Leydig cell
- adipocyte
- contractile cell
- melanocyte
- mesenchymal cell
- mural cell
- myofibroblast cell
- notochordal cell
- nucleus pulposus cell of intervertebral disc
- odontocyte
- osteocyte
- pericyte
- renal filtration cell
- skeletogenic cell
- stromal cell
- telocyte
Muscle:
- cell of skeletal muscle
- muscle cell
Neuronal:
- neural cell
- neural stem cell
- neuron
- sensory receptor cell
Other:
- abnormal cell
- anucleate cell
- apoptosis fated cell
- ascospore
- bladder cell
- bone cell
- bone marrow cell
- brain vascular cell
- cardiocyte
- cell
- cell in vitro
- ciliated cell
- circulating cell
- crystallin accumulating cell
- cultured cell
- diploid cell
- endocrine cell
- eukaryotic cell
- fungal spore
- glycogen accumulating cell
- hair follicle cell
- haploid cell
- hypothalamus cell
- inflammatory cell
- inner cell mass cell
- interstitial cell
- kidney cell
- lower urinary tract cell
- malignant cell
- motile cell
- multinucleate cell
- neoplastic cell
- nephrocyte
- nucleate cell
- perivascular cell
- pigment cell
- pituitary gland cell
- primary cultured cell
- protoplast
- retinal cell
- salivary gland cell
- sebaceous gland cell
- secretory cell
- sexual spore
- single nucleate cell
- spheroplast
- supporting cell
- syncytial cell
Stem/progenitor:
- blastoderm cell
- embryonic cell (metazoa)
- mesodermal cell
- neural progenitor cell
- precursor cell
- progenitor cell
- stem cell
- transit amplifying cell
- zygote
Trophoblast/placental:
- extraembryonic cell
