D01 Inorganic Chemicals:
- Inorganic Chemicals
D02 Organic Chemicals:
- Organic Chemicals
D03 Heterocyclic Compounds:
- Heterocyclic Compounds
D04 Polycyclic Compounds:
- Polycyclic Compounds
D05 Macromolecular Substances:
- Macromolecular Substances
D06 Hormones, Hormone Substitutes, and Hormone Antagonists:
- Hormones, Hormone Substitutes, and Hormone Antagonists
D07 Enzyme Inhibitors:
- Enzyme Inhibitors
D08 Enzymes and Coenzymes:
- Enzymes and Coenzymes
D09 Carbohydrates:
- Carbohydrates
D10 Lipids:
- Lipids
D11 Growth Substances, Pigments, Vitamins:
- Growth Substances, Pigments, Vitamins
D12 Amino Acids, Peptides, and Proteins:
- Amino Acids, Peptides, and Proteins
D13 Nucleic Acids, Nucleotides, and Nucleosides:
- Nucleic Acids, Nucleotides, and Nucleosides
D20 Complex Mixtures:
- Complex Mixtures
D23 Biological Factors:
- Biological Factors
D26 Pharmaceutical Preparations:
- Pharmaceutical Preparations
D27 Chemical Actions and Uses:
- Chemical Actions and Uses
D25 Biomedical and Dental Materials:
- Biomedical and Dental Materials
