C01 Infections:
- Infections
C04 Neoplasms:
- Neoplasms
C05 Musculoskeletal Diseases:
- Musculoskeletal Diseases
C06 Digestive System Diseases:
- Digestive System Diseases
C07 Stomatognathic Diseases:
- Stomatognathic Diseases
C08 Respiratory Tract Diseases:
- Respiratory Tract Diseases
C09 Otorhinolaryngologic Diseases:
- Otorhinolaryngologic Diseases
C10 Nervous System Diseases:
- Nervous System Diseases
C11 Eye Diseases:
- Eye Diseases
C12 Urogenital Diseases:
- Urogenital Diseases
C13 Female Urogenital Diseases and Pregnancy Complications:
- Female Urogenital Diseases and Pregnancy Complications
C14 Cardiovascular Diseases:
- Cardiovascular Diseases
C15 Hemic and Lymphatic Diseases:
- Hemic and Lymphatic Diseases
C16 Congenital, Hereditary, and Neonatal Diseases and Abnormalities:
- Congenital, Hereditary, and Neonatal Diseases and Abnormalities
C17 Skin and Connective Tissue Diseases:
- Skin and Connective Tissue Diseases
C18 Nutritional and Metabolic Diseases:
- Nutritional and Metabolic Diseases
C19 Endocrine System Diseases:
- Endocrine System Diseases
C20 Immune System Diseases:
- Immune System Diseases
C21 Disorders of Environmental Origin:
- Disorders of Environmental Origin
C22 Animal Diseases:
- Animal Diseases
C23 Pathological Conditions, Signs and Symptoms:
- Pathological Conditions, Signs and Symptoms
C24 Occupational Diseases:
- Occupational Diseases
C25 Chemically-Induced Disorders:
- Chemically-Induced Disorders
C26 Wounds and Injuries:
- Wounds and Injuries
